version: "3.8"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file: .env
    volumes:
      - drafts:/drafts
    depends_on: [redis]
    restart: unless-stopped
  worker:
    build:
      context: .
      dockerfile: Dockerfile.workers
    command: celery -A workers.tasks worker --loglevel=info
    env_file: .env
    volumes:
      - drafts:/drafts
    depends_on: [redis]
    restart: unless-stopped
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.workers
    command: celery -A workers.tasks beat --loglevel=info
    env_file: .env
    depends_on: [redis]
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    restart: unless-stopped
volumes:
  drafts:
